### ISSUE TITLE
[Bug]: global plan does not get published

### ISSUE THREAD

**Issue by vogelnik** [ll7/paf22#135]
### Current Behavior

Rostopic ``carla/hero/global_plan`` doesnt get published at all
(same for ``carla/hero/global/plan_gnss``)

### Expected Behavior

 like mentioned [here](https://leaderboard.carla.org/get_started/) in chapter 3.4.2 carla should publish the global route in the topics ``carla/hero/global_plan`` and  ``carla/hero/global/plan_gnss``

I figuered that leaderboard_evaluator.py calls set_global_plan(...) which is defined in ROS1Agent (ros1_agent.py) which PAF22Agent (agent.py) heritages from. In set_global_plan(...) ``carla/hero/global_plan`` and  ``carla/hero/global/plan_gnss`` are published but it doesnt work somehow...

### How to reproduce the issue

git checkout 71-feature-navigation-data-research

run the project (e.g. b5 run) then run the following in terminal:
```
b5 shell
  source "/opt/ros/noetic/setup.bash"
  source "/catkin_ws/devel/setup.bash"
  rostopic info /carla/hero/global_plan    (or rostopic echo /carla/hero/global_plan)
```

**Comment by nylser** [comment]
Are you trying this while using the "dev-environment"? The leaderboard_evaluator is not started by default. Therefore, for our testing, we need to publish the global plan ourselves in the dev environment

**Comment by nylser** [comment]
Oh no, very sorry for the confusion that caused :(
The next time, don't hesitate to ask in Discord or somewhere else!
