### ISSUE TITLE
Minimal Viable Vehicle

### ISSUE THREAD

**Issue by ll7** [ll7/paf22#27]
### Description

Fahren
- **Mit "leeren" Grundkomponenten erstellen**
- Erstmal geradeaus fahren
- Throttle setzen
- Anfängliche Sensor Grundkonfiguration
- Auto aus Carla Leaderboard auswählen

**Comment by ll7** [comment]
blocked by #28

**Comment by ll7** [comment]
Wie weit ist dieses Fahrzeug davon entfernt, auch schon hochgeladen zu werden? Welche Baustellen sind dafür noch offen?

**Comment by nylser** [comment]
additionally adding improvements to the agent Dockerfile, so it does no longer run as root
