### ISSUE TITLE
Setup dev environment

### ISSUE THREAD

**Issue by ll7** [ll7/paf22#28]
### Description

- Erweiterung des Install Scripts?
- Sprache definieren
- Code Style
- Doc Style
- Git Style
- Linter
- Git commit hook
- Github action
- Dockerisierung vll. separat.
- License Vorschlag

**Comment by ll7** [comment]
Beispiele, wo es geht.
Vollständige umsetzung mit option zur Veränderung

**Comment by ll7** [comment]
In welcher Sprache soll denn kommentiert und dokumentiert werden? Englisch und/oder Deutsch?

**Comment by nylser** [comment]
Trying to start with Dockerization in place, for a consistent and easy-to-setup enviromment.

**Comment by nylser** [comment]
Additionally:
- what IDE should be used, can we generate the same docstrings with PyCharm and VSCode
- what is the deal with VSCodes devcontainer? Or should we use PyCharm for development?
- => Based on this, update the documentation
