### ISSUE TITLE
Sammeln und Priorisieren von Fahrfunktionen

### ISSUE THREAD

**Issue by ll7** [ll7/paf22#30]
### Description

Ziel ist Vorschlag:
- Was gibt es für Fahrfunktionen: Siehe Carla Leaderboard -> Welche Verkehrssituationen gibt es?
- Welche Relevanz und Komplexität haben die einzelnen Fahrfunktionen
- **Am wichtigsten: Priorität**

**Comment by JoKircher** [comment]
Resolved by #60
