### ISSUE TITLE
Schnittstellen definieren und festhalten

### ISSUE THREAD

**Issue by ll7** [ll7/paf22#33]
### Description

Schnittstellen zwischen Perception & Planning & Acting definieren und festhalten.

Ggf. anhand von ROS Topics und Message Types, oder eines Definitions Files.

Änderungen danach nur noch über PRs mit der entsprechenden Kommunikation an alle Betroffenen.

Ziel bis 23.11:
(Vorschlag)
- Diagramm über Aufgabenbereiche für:
  - Perception
  - Planning
  - Acting

=> Mögliche Orientierung: Architektur aus vorherigen Projekten

**Comment by nylser** [comment]
@MarcoRiedenauer Perception
@erlbacsi Planning
@Julian-Graf Acting

**Comment by nylser** [comment]
Boards:
https://miro.com/
https://app.diagrams.net/
https://excalidraw.com/

**Comment by nylser** [comment]
Treffen am 23. um Ergebnisse zu Diskutieren
