### ISSUE TITLE
Continous Integration - Driving

### ISSUE THREAD

**Issue by nylser** [ll7/paf22#38]
### Description

Continously testing the developed car, most optimally using the CARLA leaderboard.
This way we can get a continous automated scoring of our driving systems.

Requires:
- GitHub Action for execution 
- System with GPU that can run the test

**Comment by ll7** [comment]
Will there also be an issue for "CI - Building"? For your perspective, is that one issue, or should there be a distinction between `Building` and `Driving`?

**Comment by nylser** [comment]
@ll7 yes, that was the thought behind the title. Maybe the Building and codestyle pipeline should run separately
