### ISSUE TITLE
[Feature]: Implement Pure Pursuit Controller

### ISSUE THREAD

**Issue by schwalga** [ll7/paf22#67]
### Description

Implement node that calculates steering angle based on Pure Pursuit Controller

### Definition of Done

Publishes correct steering angle based on Pure Pursuit Controller

**Comment by Julian-Graf** [comment]
Test with Dummy Trajectory

**Comment by schwalga** [comment]
While the pure pursuit controller appears to be working now, it can't be tested with the current state of the GPS sensor.
Since simple filters are not working, I created [a separate issue](#131) to implement a more sophisticated filter.

After removing said simple attempt, this controller could be considered done.
