### ISSUE TITLE
[Bug]: all "published" ROS Topics are empty

### ISSUE THREAD

**Issue by vogelnik** [ll7/paf22#85]
### Current Behavior

when starting the simulation with b5 run there are a lot of published topics (with `rostopic list` you can print them all).
But when i try to print the published messages to screen (with `rostopic echo <topic>`) there are none because i think theres something wrong with the clock.

Backlog:
```
(paf) imech037@auxme-imech037:~/PAF/paf22$ rostopic list

/carla/debug_marker
/carla/hero/Center/camera_info
/carla/hero/Center/image
/carla/hero/GPS
/carla/hero/IMU
/carla/hero/LIDAR
/carla/hero/OpenDRIVE
/carla/hero/RADAR
/carla/hero/Speed
/carla/hero/global_plan
/carla/hero/global_plan_gnss
/carla/hero/status
/carla/hero/vehicle_control_cmd
/carla/scenario/walker_control_cmd
/carla/status
/carla/world_info
/client_count
/clock
/connected_clients
/rosout
/rosout_agg
/tf

(paf) imech037@auxme-imech037:~/PAF/paf22$ rostopic echo /carla/hero/IMU
WARNING: no messages received and simulated time is active.
Is /clock being published?
^C
(paf) imech037@auxme-imech037:~/PAF/paf22$ rostopic echo /carla/hero/GPS
WARNING: no messages received and simulated time is active.
Is /clock being published?
^C
(paf) imech037@auxme-imech037:~/PAF/paf22$ rostopic echo /clock
WARNING: no messages received and simulated time is active.
Is /clock being published?
^C
(paf) imech037@auxme-imech037:~/PAF/paf22$ rosparam set use_sim_time false
(paf) imech037@auxme-imech037:~/PAF/paf22$ rostopic echo /clock
^C
(paf) imech037@auxme-imech037:~/PAF/paf22$ rostopic echo /carla/hero/GPS
```

### Expected Behavior

The topics should be filled with (sensor-) data to be read.

### How to reproduce the issue

(i was working on branch #71  [71-feature-navigation-data-research](https://github.com/ll7/paf22/tree/71-feature-navigation-data-research) for issue #71 should be up-to-date with main though)
- b5 run

when world and agent got started open another terminal:
- rostopic list (to see available <topic>) 
- rostopic echo <topic>

**Comment by timdreier** [comment]
May we introduce a proxy command like `b5 rostopic @`?

**Comment by nylser** [comment]
@timdreier good idea, but I wouldn't limit it to "rostopic". Rather something like `b5 cmd @` that runs the command inside of the Agent container?

**Comment by timdreier** [comment]
@nylser this does already exist. You can just call b5 shell agent rostopic list.

Your command would just make the command shorter, so maybe it's useful even if it's a duplicate?

**Comment by nylser** [comment]
@timdreier You're right. Yes, I was thinking of it as a duplicate shortcut as we might need this more often.

**Comment by timdreier** [comment]
@nylser I just created shortcuts like `b5 rostopic list` for the common ROS commands. This seems shorter than something like `b5 cmd rostopic list`, since the last one would be pretty similar to `b5 shell agent rostopic list`.
