### ISSUE TITLE
[Bug]: GitHooks won't work when using visual commit in PyCharme

### ISSUE THREAD

**Issue by timdreier** [ll7/paf22#97]
### Current Behavior

```
Starting git hooks
No python files in commit, skip python linting
.git/hooks/pre-commit: 9: ././build/hooks/pre-commit.d/20-markdown.sh: b5: not found
```

### Expected Behavior

Commit works without an error.

### How to reproduce the issue

* commit via the GUI in PyCharme

**Comment by timdreier** [comment]
The problem seems that the Workstations in the lab use Conda, while PyCharme uses the native environment:

https://stackoverflow.com/questions/56743628/git-hooks-inside-pycharm-running-in-incorrect-environment

Could you try the following:

⌨️ Run the following commands
```
$ conda deactivate
$ apt-get install python pip
$ pip install b5
```

🔄 Restart

⌨️ Check if it works

```
$ conda deactivate
$ b5
```

After that you should see:

```
b5 1.3.3
Executing task help

Usage: b5 <task> <args>

Tasks:
     1	help

Task exited ok
```

Then, try to commit again using the PyCharme GUI.

**Comment by JoKircher** [comment]
@timdreier this fix resolved my issue. You should add it to the documentation. Thank you for the quick response!!!

Btw. you might want to add a `sudo` to `apt-get install python pip`
